github: [jonassterud]
custom: ['https://www.paypal.com/paypalme/jonassterud', 'https://www.blockchain.com/btc/address/bc1q3sxc0pgglkcxusgux0y22erjywswqs0acg3rgl', 'https://blockchair.com/litecoin/address/MTjBkW2ChQEC1MNvA5HqCmsuAY8j8FQfkt']
